name: Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Make deployment GET request
      run: |
        curl <just add your URL>
    
    - name: Premium Bot Deployment
      run: |
        curl <just add your URL>
