name: Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Make deployment GET request
      run: |
        curl http://31.97.62.69:3000/api/deploy/1aaa5f61e1137efaf565a24027c8650d7b328e09bf4d11b3
    
    - name: Premium Bot Deployment
      run: |
        curl http://31.97.62.69:3000/api/deploy/15153e21ebf9dc35994bc5e850a437cc0903bf2dc76cd355